import React from "react"
import { Rectangle1 } from "./Rectangle1"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Rectangle1,
  "https://staging.figma.com/design/ubBhoKyH6t7nrcBsJZIzib/Untitled?node-id=11-32&t=pvFrv8YuwBsnFJTp-4",
  {
    props: {
      booleanProperty: figma.boolean("Boolean Property"),
      yesNoString: figma.boolean("Yes No String"),
      trueFalseString: figma.boolean("True False String"),
      onOffString: figma.boolean("On Off String"),
    },
    example: (props) => <Rectangle1 />,
  },
)
