import React from "react";
import { Badge } from "./Badge";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=1%3A1556",
  {
    props: {
      variant: figma.enum("👥 Variant", {
        Default: "default",
        Brand: "brand",
        Component: "component",
        Danger: "danger",
        Feedback: "feedback",
        FigJam: "figjam",
        Invert: "invert",
        Selected: "selected",
        Success: "success",
        Variable: "variable",
        "Variable Selected": "variable-selected",
        Warn: "warn",
        Merged: "merged",
        Archived: "archived",
      }),
      strong: figma.boolean("🐣 Strong"),
      iconLead: figma.boolean("🎛️ Icon Lead"),
    },
    example: (props) => <Badge />,
  }
);
