import React from "react";
import { Button } from "./Button";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=1%3A145",
  {
    props: {
      hotkey: figma.boolean("👁️ Hotkey"),
      label: figma.string("🎛️ Label"),
      icon: figma.instance("↪ Icon"),
      variant: figma.enum("👥 Variant", {
        Primary: "primary",
        Destructive: "destructive",
        Inverse: "inverse",
        Success: "success",
        FigJam: "figjam",
        Secondary: "secondary",
        "Secondary Destruct": "secondary-destruct",
        Link: "link",
        "Link Danger": "link-danger",
      }),
      size: figma.enum("👥 Size", {
        Default: "default",
        Large: "large",
        Wide: "wide",
      }),
      state: figma.enum("🐣 State", {
        Default: "default",
        Active: "active",
        Focused: "focused",
      }),
      disabled: figma.boolean("🎛️ Disabled"),
      iconLead: figma.boolean("🎛️ Icon Lead"),
    },
    example: (props) => {
      const [value, setValue] = React.useState<number>(props.variant);
      return <Button />;
    },
  }
);
