import React from "react";
import ButtonIcon from "./ButtonIcon";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonIcon,
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=374-1016&m=dev",
  {
    props: {
      leftIcon: figma.enum("Show LeftIcon", {
        true: figma.instance("LeftIcon"),
        false: undefined,
      }),
      textContent: figma.textContent("Text Link"),
      rightIcon: figma.enum("Show RightIcon", {
        true: figma.instance("RightIcon"),
        false: undefined,
      }),
      radioButton: figma.nestedProps("Radio Button__", {
        checked: figma.string("🐣 State"),
        disabled: figma.boolean("🎛️ Label"),
      }),
      radioButtonX: figma.nestedProps("Radio Button ", {
        checked: figma.string("🐣 State"),
        disabled: figma.boolean("🎛️ Label"),
      }),
    },
    example: (props) => (
      <ButtonIcon>
        <>
          {props.radioButton.checked} {props.radioButton.disabled}
        </>
        <>
          {props.radioButtonX.checked} {props.radioButtonX.disabled}
        </>
      </ButtonIcon>
    ),
  }
);
