import React from "react"
import { Checkbox } from "./Checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=1%3A1727",
  {
    props: {
      label: figma.string("Label"),
      isInvalid: figma.boolean("isInvalid"),
    },
    example: (props) => <Checkbox label={props.label} isInvalid={props.isInvalid} />,
  },
)
