import React from "react"
import { Dropdown } from "./Dropdown"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Dropdown,
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=68%3A1350",
  {
    props: {
      label: figma.string("Label"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Active: "active",
        Disabled: "disabled",
        Error: "error",
      }),
    },
    example: (props) => <Dropdown />,
  },
)
