// import React from "react";
// import Icon from "./Icon";
// import figma from "@figma/code-connect";

// /**
//  * -- This file was auto-generated by Code Connect --
//  * None of your props could be automatically mapped to Figma properties.
//  * You should update the `props` object to include a mapping from your
//  * code props to Figma properties, and update the `example` function to
//  * return the code example you'd like to see in Figma
//  */

// figma.connect(
//   Icon,
//   "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=255%3A997",
//   {
//     props: {},
//     example: (props) => <Icon name={/* TODO */} />,
//   }
// );
