import React from "react";
import figma from "@figma/code-connect";
import Input from "./Input";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Input,
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=258-1019&t=FwNXgikLtmS1NjsQ-4",
  {
    props: {
      // errorMessage: figma.enum("State", {
      // inputMessageProps: figma
      //   .instance(".Input Message")
      //   .getProps<{ text: string }>(),
      // // }),
      inputMessage: figma.children(".Input Message"),
    },
    example: (props) => <Input errorMessage={props.inputMessage} />,
  }
);

figma.connect(
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=258-1014&m=dev",
  {
    props: {
      text: figma.textContent("Error Message"),
    },
    example: (props) => {
      <>
        2<>{props.text}</>
      </>;
    },
  }
);
