import React from "react"
import { RadioButton } from "./RadioButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RadioButton,
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=3%3A1856",
  {
    props: {
      state: figma.enum("🐣 State", {
        Default: "default",
        Focused: "focused",
      }),
      on: figma.boolean("🐣 On?"),
      label: figma.boolean("🎛️ Label"),
    },
    example: (props) => <RadioButton />,
  },
)
