import React from "react";
import { DropdownAlt } from "./DropdownAlt";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DropdownAlt,
  "https://staging.figma.com/design/XHti3mZMluUwlrDrMvfToU/Wizard-Design-System?node-id=120-1072&t=3PZcdrRegNyizXVg-4",
  {
    imports: ["import DropdownAlt from @your-library/Dropdown"],
    variant: { type: "bank-placeholder" },
    example: (props) => (
      <DropdownAlt options={undefined} onSelect={undefined} />
    ),
  }
);
